version: "0.1.0"

kafka:
  topic: "entity"
  partition: 0
  address: "localhost:9092"

database:
  driver: "postgres"
  user: "user"
  password: "password"
  host: "localhost"
  port: "5432"
  dbName: "holycrusade"
